name: Onemap Bicycle Parking Search
run-name: ${{ github.actor }} deploying Onemap Bicycle Parking Search.
on:
  push:
  workflow_dispatch:

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: List files
        run: |
          ls -lR ${{ github.workspace }}

      - name: Verify Go
        run: |
          go version
          go mod tidy
          go test ./...

      - name: Build for ARMv6 Raspberry Pi
        run: |
          GOOS=linux GOARCH=arm GOARM=6 go build -o bicyclesearch ./05_defaultMap/

      - name: Verify executable type
          run: |
            file ./bicyclesearch

      - name: Verify executable size
          run: |
            ls -lh ./bicyclesearch
