name: Onemap Bicycle Parking Search
run-name: ${{ github.actor }} deploying Onemap Bicycle Parking Search.
on:
  push:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v5

      - name: List files
        run: |
          ls -lR ${{ github.workspace }}

      - name: Verify Go
        run: |
          go version
          go mod tidy
          go test ./...

      - name: Build for ARMv6 Raspberry Pi
        run: |
          GOOS=linux GOARCH=arm GOARM=6 go build -o bicyclesearch ./05_defaultMap/

      - name: Verify executable type
        run: |
          file ./bicyclesearch

      - name: Verify executable size
        run: |
          ls -lh ./bicyclesearch

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: bicyclesearch-arm
          path: bicyclesearch

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH keys
        run: |
          mkdir -p .ssh
          echo "${{ secrets.RASPKEY }}" > .ssh/id_ed25519
          chmod 600 .ssh/id_ed25519
      - name: Verify SSH connectivity
        run: |
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 22322 ls -al
      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          name: bicyclesearch-arm
          path: bicyclesearch
      - name: scp binary to rasp
        run: |
          scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -P 22322 ./bicyclesearch siuyin@rasp.beyondbroadcast.com:
      - name: Verify copy
        run: |
          ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -p 22322 siuyin@rasp.beyondbroadcast.com ls -lh bicyclesearch
